### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'movielens_attributes/final_embedding_50_5000.txt'

### ISSUE THREAD

**Issue by OuyKai** [ReyonRen/MFGAN#2]
您好，我尝试复现您的代码，但是出现文件缺失的报错：FileNotFoundError: [Errno 2] No such file or directory: 'movielens_attributes/final_embedding_50_5000.txt'
请问能否提供一下数据文件？

**Comment by ReyonRen** [comment]
您好，因为我们知识图谱数据使用了KB4REC数据集，它不是公开的，所以这部分数据由于license原因不能公开。
您可以使用其他属性信息构造数据文件，也是有效果的。

**Comment by meiyouyuyu** [comment]
> 您好，因为我们知识图谱数据使用了KB4REC数据集，它不是公开的，所以这部分数据由于license原因不能公开。 您可以使用其他属性信息构造数据文件，也是有效果的。

那能告诉我这些数据的形式吗

**Comment by meiyouyuyu** [comment]
> > 您好，因为我们的知识图谱数据使用了KB4REC数据集，它不是公开的，所以这个属性数据部分由于许可原因不能公开。您可以使用其他信息构造数据文件，也是有效果的。
> 
> 那可以告诉我这些数据的形式吗

因为您论文里面涉及三个未知数据集，您能告诉我这些数据集的形式吗？final_embedding_50_5000.txt'     
 movielens_popularity.txt   movielens_category.txt
